name: predator
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.5
  - pip
  - numpy=1.24.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - pillow=10.4.0
  - h5py=3.11.0
  - opencv=4.10.0
  - jupyter=1.0.0
  - notebook=7.2.0
  - pip:
    - torch==2.4.1
    - torchvision==0.19.1
    - torchaudio==2.4.1
    - nibabel==5.2.1
    - tqdm==4.38.0
    - open3d==0.18.0
    - easydict==1.11
    - coloredlogs==15.0.1
    - PyYAML==6.0.1
    - tensorboardX==2.6.2.2
    - vtk-visualizer==0.9.6
    - gitpython==3.1.43
    - requests==2.32.4
    - opencv-python==4.10.0.84